POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "ever321@gmail.com",
  "password": "ever123"
}

### Get the currently signedin user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Authenticate a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "ever321@gmail.com",
  "password": "ever123"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/3

### Find a particular user with a given email
GET http://localhost:3000/auth?email=vinicius@gmail.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/555

### Update a user with a given id and a body request
PATCH http://localhost:3000/auth/555
content-type: application/json

{
  "email": "soares123EMAIL@gmail.com",
  "password": "MeuNovoPassword"
}
